FROM python:3.8-slim

WORKDIR /app

COPY src/client.py .
COPY requirements.txt .

# Install only required packages for client (no torch needed)
RUN pip install --no-cache-dir flask requests

ENTRYPOINT ["python", "client.py"] 