FROM python:3.8-slim

WORKDIR /app

COPY src/server.py .
COPY model.pt .
COPY requirements.txt .

# Install dependencies without CUDA
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "server.py"] 