FROM python:3.8-slim

WORKDIR /app

# Install required packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Create a models directory
RUN mkdir -p /app/models

# Copy the source code
COPY src/ .

# Expose the port for the API
EXPOSE 5000

# Run the server
CMD ["python", "server.py"] 